### ISSUE TITLE
2015-01-08: build without stdc++ broken

### ISSUE THREAD

**Issue by tru7** [Makki1/knxd#22]
Commit: e9f630adbe2409dd8ab29bc58a7fc4179c0fea08
Configure: --enable-eibnetip --enable-eibnetiptunnel --enable-eibnetipserver --enable-usb --with-pth=/sw/pkgs/pthsem-2.0.8 --without-libstdc
Build system: Ubuntu 14.04 LTS
Still works with code from 2014-12-21 on same build system, now it's broken
Also Cross-Compile for OpenWrt is broken now
So, I guess code base is broken in master branch

returns error for make:
Making all in server
make[3]: Entering directory `/home/truniger/compile/scratch/knxd/src/server'
gcc -DHAVE_CONFIG_H -I. -I../..  -I../../src/libserver -I../../src/backend -I../../src/common -I../../src/usb -I/sw/pkgs/pthsem-2.0.8/include -I/usr/include/libusb-1.0     -g -O2 -fno-rtti -fno-exceptions -MT knxd.o -MD -MP -MF .deps/knxd.Tpo -c -o knxd.o knxd.cpp
mv -f .deps/knxd.Tpo .deps/knxd.Po
/bin/bash ../../libtool  --tag=CXX   --mode=link gcc  -g -O2 -fno-rtti -fno-exceptions   -o knxd knxd.o  ../backend/libbackend.a ../libserver/libeibstack.a ../common/libcommon.a ../usb/libusb.a -L/sw/pkgs/pthsem-2.0.8/lib -lpthsem -lusb-1.0
libtool: link: gcc -g -O2 -fno-rtti -fno-exceptions -o knxd knxd.o  ../backend/libbackend.a ../libserver/libeibstack.a ../common/libcommon.a ../usb/libusb.a -L/sw/pkgs/pthsem-2.0.8/lib /sw/pkgs/pthsem-2.0.8/lib/libpthsem.a -L/sw/lib -lusb-1.0
knxd.o: In function `startServer(Layer3*, Trace*, char const*)':
/home/truniger/compile/scratch/knxd/src/server/knxd.cpp:302: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
knxd.o: In function `std::string::_Rep::_M_dispose(std::allocator<char> const&)':
/usr/include/c++/4.8/bits/basic_string.h:240: undefined reference to `std::string::_Rep::_S_empty_rep_storage'
/usr/include/c++/4.8/bits/basic_string.h:249: undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../libserver/libeibstack.a(eibnetserver.o): In function `std::string::_Rep::_M_dispose(std::allocator<char> const&)':
/usr/include/c++/4.8/bits/basic_string.h:240: undefined reference to `std::string::_Rep::_S_empty_rep_storage'
/usr/include/c++/4.8/bits/basic_string.h:249: undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../libserver/libeibstack.a(eibnetserver.o): In function `_Alloc_hider':
/usr/include/c++/4.8/bits/basic_string.h:275: undefined reference to `std::string::_Rep::_S_empty_rep_storage'
../libserver/libeibstack.a(eibnetserver.o): In function `std::string::operator=(std::string const&)':
/usr/include/c++/4.8/bits/basic_string.h:547: undefined reference to `std::string::assign(std::string const&)'
collect2: error: ld returned 1 exit status
make[3]: *** [knxd] Error 1
make[3]: Leaving directory `/home/truniger/compile/scratch/knxd/src/server'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/truniger/compile/scratch/knxd/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/truniger/compile/scratch/knxd'
make: *** [all] Error 2

**Comment by p3root** [comment]
have you tried to remove your local copy and clone the repo again? try to run ./bootstrap.sh and configure again.

**Comment by do13** [comment]
Someone changed knxd to use STL strings (std::string) instead of knxd own string class.
It looks like https://github.com/Makki1/knxd/commit/4e9735752a3b3e5ed124ec50f073f1fcd65e6b33 was the root cause.

**Comment by tru7** [comment]
Yes, I do a fresh clone for every run and compare the output between the runs to look for suspicious differences.

**Comment by RichiH** [comment]
@tru7 `git bisect` is quicker... http://git-scm.com/docs/git-bisect

**Comment by timowi** [comment]
why the hell are you configure with "--without-libstdc"??? No wonder you miss stdc++ functions

**Comment by do13** [comment]
No. In the past it was possible to compile eibd with "--without-libstdc".
Commit 4e97357 added std::string in eibnetserver.cpp and eibnetserver.h. There is no other usage of std::string in the whole sourcecode.

**Comment by p3root** [comment]
Stl is standard c++ and should be usable in every c++ project. It's (mostly, MS is working on it ;)) cross-compile able and easy to use. So why not stl??
________________________________
Von: Timo<mailto:notifications@github.com>
Gesendet: ‎08.‎01.‎2015 23:14
An: Makki1/knxd<mailto:knxd@noreply.github.com>
Cc: Patrik Pfaffenbauer<mailto:patrik.pfaffenbauer@p3.co.at>
Betreff: Re: [knxd] 2015-01-08: build broken (#22)

why the hell are you configure with "--without-libstdc"??? No wonder you miss stdc++ functions

---

**Comment by timowi** [comment]
yeah, but is there is any reason to build without stdc++? Maybe there was a reason with bcusdk. But now we should just switch to use this instead of keeping our own implementations of basic functionality.

**Comment by p3root** [comment]
Nope. Ther is definetly no reason.
________________________________
Von: Timo<mailto:notifications@github.com>
Gesendet: ‎08.‎01.‎2015 23:31
An: Makki1/knxd<mailto:knxd@noreply.github.com>
Cc: Patrik Pfaffenbauer<mailto:patrik.pfaffenbauer@p3.co.at>
Betreff: Re: [knxd] 2015-01-08: build broken (#22)

yeah, but is there is any reason to build without stdc++? Maybe there was a reason with bcusdk. But now we should just switch to use this instead of keeping our own implementations of basic functionality.

---

**Comment by do13** [comment]
The reason is flash space on some.openwrt devices. libstdc++ adds several MBytes.

**Comment by timowi** [comment]
@do13 are there really devices without dynamic libstd++?  Can you please provide some examples.

For future development it will be hard to completely work without std++. There have to be very good reasons to do this.

**Comment by p3root** [comment]
My libstd on an embeeded linux has 762K.

**Comment by timowi** [comment]
I created a issue to remove this option 
https://github.com/Makki1/knxd/issues/23

libstdc++ several MB? Please provide more information. Are there really platforms for knxd where no application uses libstdc++? It do not think it's worth the effort to pull this all the way.

**Comment by do13** [comment]
IIRC openwrt builds eibd/knxd without libstc++ exactly for the flash space reason. 
https://github.com/openwrt/packages/blob/2993533747d777bafa1c7f1f137c27824e50d06c/net/knxd/Makefile
Personally I don't care about this. libstc++ is already in my image and I don't use openwrt anymore.
But I think the creator of this issue has a need for this.

**Comment by timowi** [comment]
I changed it to the internal string class for now.

Further discussion about not using libstdc++ in issue https://github.com/Makki1/knxd/issues/23

**Comment by do13** [comment]
Good idea.
For now knxd should behave and build like the eibd version.
In future such changes should be announced and discussed in advance.

**Comment by tru7** [comment]
@do13 I fully agree with your last comment.
@timowi thank you for handling this so quick and so well. It works again. I'll add some info in issue #23
